### ISSUE TITLE
Loading indicator in UI

### ISSUE THREAD

**Issue by davidvanrooij** [davidvanrooij/COMP0072#10]
Sometimes it is not clear that the request has been sent to the API. Maybe fix it with some sort of loading icon when you press on the classify button?

**Comment by capimx** [comment]
I agree, the problem is noticeable when you try to classify after some time it hasn't been used. Given that we use the free version of Heroku, the web dyno sleeps after 30 min of inactivity, so the next request will take longer, while the process awakes.
