### ISSUE TITLE
Investigate and modify to allow CORS headers

### ISSUE THREAD

**Issue by capimx** [davidvanrooij/COMP0072#13]
Currently, the API and the website are hosted in different parts, so we need an additional header [Cross-Origin Resource Sharing (CORS)] to allow this. Currently, the end user is not able to run it as it is.

These are some alternatives:
- Investigate about how to create a trusted relationship
- Investigate if the HTTP request done to the API can be just modified

**Comment by davidvanrooij** [comment]
Fixed in 0347948ce3b481736783c17fd7e5506dfb4838bc. Closing issue.
