### ISSUE TITLE
Error prone input

### ISSUE THREAD

**Issue by davidvanrooij** [davidvanrooij/COMP0072#15]
The following input needs an investigation on why and how these results are produced

<img width="892" alt="screenshot 2018-12-02 at 10 25 08" src="https://user-images.githubusercontent.com/9198393/49338687-b8845e80-f61c-11e8-89b2-61669e511578.png">

**Comment by capimx** [comment]
could be investigated with #17

**Comment by davidvanrooij** [comment]
Since this type of 7 was not present in the training data and therefore faulty. The 1 now gets classified, they were occasionally dropped before when calculating the percentage of the canvas. Fixed in 29897b8fdc95b7d19d68ea0286b6c496bbbf9316. 

Closing for now.
